### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Innocent259** [JansueT/Portfolio#21]
Hi @JansueT 
You have a good design. But there are some issues we would recommend to be solved!
1. On the section engine the text in the paragraph is not responding well. please you can check if it is caused by fixed width.

**Comment by mohamedgamaleldin999999** [comment]
Hi Jansue, great work done here. 

![very close](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

# Required changes

- [ ] I suggest you use grid property for the "works" section. It would be better if it is displaying three columns and two rows just like the Figma template.
- [ ] I think it might be more user-friendly if the form inputs have around 300px min-width
