### ISSUE TITLE
RESPONSIVENESS OF THE PROJECT

### ISSUE THREAD

**Issue by Eccb7** [JansueT/Portfolio#30]
Hi :wave: @JansueT 

<img src="https://media0.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>
Amazingly, great effort has been on the project and still there a few issues that ought to be worked on.

  - Your site ain't responsive when adjusted to different screen sizes, hence, you can use the media queries or responsive values as percentages instead of pixels.

**Comment by sagieramos** [comment]
You made a great effort getting to this stage.
- Please add the put the cards in an object
